/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#1e3a5f",
        "error": "#ba1a1a",
        "inverse-primary": "#adc8f5",
        "tertiary-container": "#363a3c",
        "secondary": "#006c49",
        "on-primary": "#ffffff",
        "secondary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#adc8f5",
        "surface-container-low": "#eff4ff",
        "background": "#f8f9ff",
        "on-surface": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "on-tertiary-fixed": "#191c1e",
        "tertiary-fixed": "#e0e3e5",
        "on-tertiary-fixed-variant": "#444749",
        "on-tertiary": "#ffffff",
        "secondary-container": "#6cf8bb",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#005236",
        "surface": "#f8f9ff",
        "primary-fixed": "#d5e3ff",
        "surface-container-lowest": "#ffffff",
        "surface-tint": "#455f87",
        "primary": "#022448",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed": "#002113",
        "on-primary-container": "#8aa4cf",
        "surface-container-high": "#dce9ff",
        "surface-bright": "#f8f9ff",
        "error-container": "#ffdad6",
        "on-background": "#0b1c30",
        "on-primary-fixed": "#001c3b",
        "on-primary-fixed-variant": "#2d486d",
        "surface-container": "#e5eeff",
        "on-secondary-container": "#00714d",
        "on-surface-variant": "#43474e",
        "tertiary-fixed-dim": "#c4c7c9",
        "inverse-on-surface": "#eaf1ff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "outline-variant": "#c4c6cf",
        "tertiary": "#212426",
        "on-error-container": "#93000a",
        "outline": "#74777f",
        "inverse-surface": "#213145",
        "on-tertiary-container": "#a1a3a5"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "base": "4px",
        "container-max": "1440px",
        "sm": "8px",
        "lg": "24px",
        "xl": "40px",
        "gutter": "24px",
        "md": "16px",
        "xs": "4px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
        "tabular-nums": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "500" }],
        "tabular-nums": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      }
    },
  },
  plugins: [],
}
